### ISSUE TITLE
Project Stage 1 - checklist

### ISSUE THREAD

**Issue by szymon037** [szymon037/TPUM_SO_RG#2]
# Project Stage 1 Checklist

- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [x] Object model representing process data
- [x] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [ ] `Data` API is abstract
- [x] `Logic` layer is clearly stated using language terms only
- [ ] `Logic` API is clearly stated
- [ ] `Logic` uses only the abstract `Data` layer API
- [x] `Presentation` layer is clearly stated using language terms only
- [ ] mvvm and xaml is applied to implement GUI
- [ ] rective and interactive programming is used
- [ ] Unit Test - layers are tested independently using abstract API
- [ ] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purpose (expected but not required)
